classdef CollisionRatesReaderRawFormat < CollisionRatesReader
    
    methods(Static=true)
        
        function Rates = CreateCollisionRatesFromFile (FileName, CollisionPartner, MoleculeData, CollisionFactor)
            
            if nargin < 4; CollisionFactor = 1; end
            
            collisionRates = CollisionRatesReaderRawFormat.readCollisionRatesFile (FileName);
            collisionRates(2:end, 3:end) = CollisionFactor*collisionRates(2:end, 3:end);
            Rates = CollisionRates(MoleculeData, CollisionPartner, collisionRates);
            
        end
        
    end
    
    methods(Static=true,Access = private, Hidden=true)
        
        function CollisionRates = readCollisionRatesFile(FileName)
            %IMPORTFILE(FILETOREAD1)
            %  Imports data from the specified file
            %  FILETOREAD1:  file to read
            
            %  Auto-generated by MATLAB on 03-Aug-2009 16:49:13
            
            % Import the file
            rawData1 = importdata(FileName);
            
            % For some simple files (such as a CSV or JPEG files), IMPORTDATA might
            % return a simple array.  If so, generate a structure so that the output
            % matches that from the Import Wizard.
            [unused,name] = fileparts(FileName);
            newData1.(genvarname(name)) = rawData1;
            
            % Create new variables in the base workspace from those fields.
            vars = fieldnames(newData1);
            
            CollisionRates = newData1.(vars{1});
            
        end
        
    end %methods
    
end %class